# Site wide configuration

title: Informe de actividades
logo: Figs/Logo_EAFIT.svg.png

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Juan David Martínez Vargas
  avatar: bio-photo.jpg
  bio: "Escuela de Ciencias Aplicadas e Ingeniería"
  email: jdmartinev@eafit.edu.co
  # Do not include the @ symbol in your Twitter username
  #twitter: laderast
  #linkedin: #username
  github: jdmartinev
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
